import type { NextPage } from "next";
import Head from "next/head";
import { CanvasContainer } from "../components/canvas/CanvasContainer";
import { MainHomeComponent } from "../components/homePage/mainHomeComponents/MainHomeComponent";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Piotr Kołodziejczyk | Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <CanvasContainer>
                <MainHomeComponent />
            </CanvasContainer>

            <footer></footer>
        </div>
    );
};

export default Home;
