import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import { Octokit } from "octokit";
import puppeteer from "puppeteer";
import { CanvasContainer } from "../components/canvas/CanvasContainer";
import { TheHomePage } from "../components/homePage/TheHomePage";
import { configPuppeteer } from "../config/configPuppeteer";

const Home: NextPage = (props) => {
    return (
        <div>
            <Head>
                <title>Piotr Kołodziejczyk | Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <CanvasContainer>
                <TheHomePage dataGithub={props} />
            </CanvasContainer>

            <footer></footer>
        </div>
    );
};

export default Home;

export async function getStaticProps() {
    const octokit = new Octokit({
        auth: process.env.TOKENGITHUB,
    });

    const dataGithub = await octokit.request("GET /users/Piotrko64", {
        username: "Piotrko64",
    });
    const { followers, public_repos } = dataGithub.data;
    return {
        props: {
            followers,
            publicRepos: public_repos,
        },
    };
}
