name: Lint and correct code by eslint
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint-fix
      - name: end Linting
        run: echo "End of Linting"
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: commit after lint
 
    
