name: Lint and correct code by eslint
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: npm ci
      - name: Lint code
        uses: npm run lint
      - name: end Linting
        uses: echo "End of Linting"
  prepare-to-deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: npm ci
      - name: Build code
        uses: npm run build
      - name: end Linting
        uses: echo "End of Building"
    
  
